language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: samiur
  password:
    secure: dI4A+hxm+lHTg9sEqI5nJNyEj2XBG0via0XahoJw+cVLaBmD48Eg0y9cP/PKyRkadY8++BTfSAOQ2y2fAdq8RH8z9M0ZahKDuePp8aRUQE9lVULv8qIIxRjs5vnv8UlFlOwVWw640olxbVB6zRVA+V87zpzSqnwPj6NSuj+OekF4zRi8pdxLXjNur1UykY/RogvqAktoNVWR5YLWV5ahk6kGNZ1jxk9tniLWmCy1eopVae5Jc1xPDzC86509cGUriklekSumFvCoIXdhcBXZgQQgNx6Ew4UCWABqCKG47zybloQ7vMLHadNbP5sAhIVbsYFTyFGJgP+A/NknZB1j/UXRxRTtg4eyzCjG59Bi4SLx6vIEQF6+ADKFXnqqDKBauaTpD744J851bltHcB3CyLJYjMjYCdrPzN4JKSXf1WJyzLSbf7UqdPDvCWcL3hQ/XnkLqB95QJSJFOAFm6gHT5QyblVzD/3xVQUGXuskUg5JK3CjK8VK1Zbu19fW2C+AvfWWxLEPYvbG/MIJ4KQmbarzOAtROYPRbLnKHTLxqq7qrsEM6b9OWMMzjQmn/rxbeIXTQc06Hv09u9YXj41ozmbMI0QBstGCTD8fvYIn/qDcOTiyu1N7BiV8bxFMkpfK/wBII7QgDSz4aZ6Kfo1cSX7bJ0o2YvEsAvS331O7D2I=
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
  distributions: sdist bdist_wheel
